# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08f1fdb7c6db844785433c9731c068b6f4db0734b10cdb707f62917ef9416cccb048339bc18b41fd3afc8daf099e09b6bab97379ac31908d4adb92985cdbbd02

test:
  secret_key_base: 387565d73b8c27198b414e3bc16b660906aa2e45c33fb01ce9ac0593f7e5f84f0976db0ae931930832570579a6ece5e102aca8e224d975066b5a6668f9f996a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
